"""initial schema

Revision ID: d8c62df4218c
Revises:
Create Date: 2026-08-27 23:55:22.533863

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# SQLModel's string columns autogenerate as sqlmodel.sql.sqltypes.AutoString,
# which Alembic does not add an import for. Included here so generated
# migrations run instead of raising NameError.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "d8c62df4218c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredient",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingredient_name"), "ingredient", ["name"], unique=False)
    op.create_table(
        "meal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("servings", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meal_name"), "meal", ["name"], unique=False)
    op.create_table(
        "mealingredient",
        sa.Column("meal_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Float(), nullable=True),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredient.id"],
        ),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meal.id"],
        ),
        sa.PrimaryKeyConstraint("meal_id", "ingredient_id"),
    )
    op.create_table(
        "weeklyplan",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("week_start_date", sa.Date(), nullable=False),
        sa.Column("day_of_week", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("meal_id", sa.Integer(), nullable=True),
        sa.Column("servings", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["meal_id"],
            ["meal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "week_start_date", "day_of_week", name="uq_weeklyplan_week_day"
        ),
    )
    op.create_index(
        op.f("ix_weeklyplan_day_of_week"), "weeklyplan", ["day_of_week"], unique=False
    )
    op.create_index(
        op.f("ix_weeklyplan_week_start_date"),
        "weeklyplan",
        ["week_start_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_weeklyplan_week_start_date"), table_name="weeklyplan")
    op.drop_index(op.f("ix_weeklyplan_day_of_week"), table_name="weeklyplan")
    op.drop_table("weeklyplan")
    op.drop_table("mealingredient")
    op.drop_index(op.f("ix_meal_name"), table_name="meal")
    op.drop_table("meal")
    op.drop_index(op.f("ix_ingredient_name"), table_name="ingredient")
    op.drop_table("ingredient")
    # ### end Alembic commands ###
